// Plain text only. These keys are shared by the advisor, reports and future UI.
const strings = {
  csvSKU: ['SKU', 'شماره قطعه'],
  csvDescription: ['Description', 'شرح'],
  csvCategory: ['Category', 'گروه'],
  csvQuantity: ['Quantity', 'تعداد بسته سفارش'],
  csvAssurance: ['Assurance', 'مبنای بررسی'],
  csvStatus: ['Technical status', 'وضعیت فنی'],
  csvReview: ['TECHNICAL REVIEW', 'بررسی فنی'],
  csvFinding: ['FINDING', 'مورد بررسی'],
  purpose: ['What are you protecting or storing?', 'هدف شما از ذخیره‌سازی چیست؟'],
  primary: ['Primary application storage', 'ذخیره‌سازی اصلی برنامه‌ها'],
  backup: ['Disk backup and recovery', 'پشتیبان‌گیری و بازیابی روی دیسک'],
  archive: ['Tape archive and offline copy', 'آرشیو نواری و نسخه آفلاین'],
  access: ['How will applications access primary storage?', 'برنامه‌ها چگونه به فضای ذخیره‌سازی اصلی دسترسی دارند؟'],
  block: ['Block / SAN', 'بلاک / SAN'], object: ['Object / S3', 'آبجکت / S3'], file: ['File / SMB / NFS', 'فایل / SMB / NFS'],
  workload: ['Which workload dominates?', 'بار کاری اصلی چیست؟'],
  iops: ['Required IOPS at the application workload (if measured)?', 'IOPS مورد نیاز در بار کاری واقعی برنامه (در صورت اندازه‌گیری)؟'],
  latencyMs: ['Maximum acceptable storage latency (milliseconds)?', 'حداکثر تأخیر قابل قبول ذخیره‌سازی (میلی‌ثانیه)؟'],
  sequentialMBps: ['Required sequential throughput (MB/s)?', 'توان عملیاتی ترتیبی مورد نیاز (مگابایت بر ثانیه)؟'],
  business: ['Business applications', 'برنامه‌های سازمانی'], virtualization: ['Virtual machines', 'ماشین‌های مجازی'],
  database: ['Databases', 'پایگاه داده'], analytics: ['Analytics and sequential data', 'تحلیل و داده‌های ترتیبی'],
  usableTB: ['How much usable capacity do you need today (decimal TB)?', 'امروز چه ظرفیت قابل استفاده‌ای نیاز دارید (ترابایت ده‌دهی)؟'],
  annualGrowthPct: ['Expected annual data growth (%)?', 'رشد سالانه مورد انتظار داده‌ها (درصد)؟'],
  years: ['How many years should the solution accommodate?', 'راهکار برای چند سال آینده ظرفیت داشته باشد؟'],
  headroomPct: ['What percentage of usable capacity should stay free?', 'چه درصدی از ظرفیت قابل استفاده خالی بماند؟'],
  protocol: ['Which host connectivity is available?', 'کدام اتصال در سمت سرورها موجود است؟'],
  fc: ['Fibre Channel', 'فیبر چنل'], iscsi: ['iSCSI Ethernet', 'اترنت iSCSI'], sas: ['Direct SAS', 'SAS مستقیم'], unknown: ['Not established', 'هنوز مشخص نیست'],
  availability: ['How critical is application availability?', 'تداوم دسترسی برنامه‌ها چقدر حیاتی است؟'],
  standard: ['Standard business service', 'سرویس سازمانی معمولی'], critical: ['Mission-critical service', 'سرویس حیاتی'],
  budgetTier: ['Which investment tier should guide the shortlist?', 'کدام سطح سرمایه‌گذاری مبنای پیشنهاد باشد؟'],
  value: ['Cost focused', 'اولویت با هزینه'], balanced: ['Balanced', 'متعادل'], performance: ['Performance / resilience focused', 'اولویت با کارایی و تاب‌آوری'],
  lifecycle: ['Should older products be considered?', 'آیا محصولات نسل قدیمی بررسی شوند؟'],
  active: ['Active in the supplied snapshot', 'فعال در اسناد ارائه‌شده'], allow_retired: ['Include older installed / used systems', 'شامل تجهیزات قدیمی نصب‌شده یا کارکرده'],
  backupTB: ['How much source data needs backup (TB)?', 'چه حجم داده مبدأ باید پشتیبان‌گیری شود (ترابایت)؟'],
  changePct: ['Daily changed data (%)?', 'درصد تغییر روزانه داده‌ها؟'],
  retentionDays: ['How many days of restore points must be retained?', 'نقاط بازیابی برای چند روز نگهداری شوند؟'],
  fullEveryDays: ['How often is a new full backup retained (days)?', 'هر چند روز یک نسخه کامل جدید نگهداری می‌شود؟'],
  backupWindowHours: ['Available backup window (hours)?', 'بازه زمانی مجاز پشتیبان‌گیری (ساعت)؟'],
  rpoMinutes: ['Maximum acceptable data loss (minutes)?', 'حداکثر از دست رفتن قابل قبول داده‌ها (دقیقه)؟'],
  rtoHours: ['Required recovery time (hours)?', 'زمان بازیابی مورد نیاز (ساعت)؟'],
  offlineCopy: ['Is an offline / offsite copy required?', 'آیا نسخه آفلاین یا خارج از سایت لازم است؟'],
  immutable: ['Is immutability or WORM required?', 'آیا تغییرناپذیری یا WORM لازم است؟'],
  yes: ['Yes', 'بله'], no: ['No', 'خیر'],
  existingLTO: ['Which LTO generation is used by existing tapes (0 for none)?', 'نوارهای موجود از کدام نسل LTO هستند (صفر یعنی نوار موجود ندارید)؟'],
  backupSoftware: ['Which backup application and version do you use?', 'از کدام نرم‌افزار پشتیبان‌گیری و نسخه آن استفاده می‌کنید؟'],
  planning: ['Engineering planning candidate; validate sizing and compatibility.', 'گزینه پیشنهادی مهندسی؛ ظرفیت و سازگاری باید بررسی شوند.'],
  role: ['Matches the requested storage role.', 'با نقش ذخیره‌سازی مورد نیاز هماهنگ است.'],
  value_fit: ['Candidate for a cost-focused SAN shortlist; prices are not known.', 'گزینه برای فهرست SAN با اولویت هزینه؛ قیمت مشخص نیست.'],
  flash_fit: ['Flash-oriented candidate for latency-sensitive workloads; performance is unverified.', 'گزینه مبتنی بر فلش برای بار حساس به تأخیر؛ کارایی تأیید نشده است.'],
  resilience_fit: ['Enterprise candidate for critical workloads; topology and service guarantees need review.', 'گزینه سازمانی برای بار حیاتی؛ توپولوژی و شرایط تضمین سرویس نیازمند بررسی است.'],
  retired: ['Discontinued in the supplied snapshot; confirm support, firmware and parts availability.', 'در اسناد ارائه‌شده متوقف شده؛ پشتیبانی، میان‌افزار و موجودی قطعات بررسی شود.'],
  missing: ['Required planning selection is missing: {category}.', 'انتخاب مورد نیاز برای طراحی انجام نشده است: {category}.'],
  scope: ['This part is not listed for the selected model in this snapshot.', 'این قطعه در اسناد این مدل فهرست نشده است.'],
  scope_unknown: ['The family document lists this part; its exact model support remains unresolved.', 'سند خانواده این قطعه را فهرست کرده؛ پشتیبانی مدل دقیق هنوز نامشخص است.'],
  form: ['Drive form factor does not match its selected enclosure.', 'اندازه درایو با محفظه انتخاب‌شده هماهنگ نیست.'],
  bay_count: ['Selected drives exceed available bays at {location}.', 'تعداد درایوها از جایگاه‌های موجود در {location} بیشتر است.'],
  bay_unknown: ['Bay allocation or enclosure capacity is not established.', 'تخصیص جایگاه یا ظرفیت محفظه مشخص نشده است.'],
  enclosure_count: ['Expansion enclosure count exceeds the documented limit.', 'تعداد محفظه‌های توسعه از حد مستند بیشتر است.'],
  raid: ['This RAID level is excluded by an encoded product rule.', 'این سطح RAID طبق قاعده مستند محصول مجاز نیست.'],
  raid_unknown: ['Product-specific RAID layout and capacity need validation.', 'آرایش RAID و ظرفیت مختص محصول باید تأیید شود.'],
  raid_count: ['Disk count is invalid for this mathematical RAID layout.', 'تعداد دیسک برای این آرایش محاسباتی RAID معتبر نیست.'],
  allocation: ['Disk groups allocate more disks than the selected drive packs supply.', 'گروه‌های دیسک بیش از تعداد درایوهای موجود در بسته‌های انتخاب‌شده تخصیص دارند.'],
  capacity_unknown: ['Usable capacity is unresolved; raw and effective capacity are not substituted.', 'ظرفیت قابل استفاده نامشخص است؛ ظرفیت خام یا مؤثر جایگزین آن نمی‌شود.'],
  capacity_short: ['The planned usable capacity is below the requirement.', 'ظرفیت قابل استفاده برآوردشده از نیاز کمتر است.'],
  capacity_estimate: ['Capacity is an estimate before metadata, system reserve and workload overhead.', 'ظرفیت پیش از کسر فراداده، ذخیره سیستم و سربار بار کاری برآورد شده است.'],
  tape_drives: ['Tape drive count exceeds the documented module limit.', 'تعداد درایو نواری از حد مستند ماژول بیشتر است.'],
  tape_modules: ['Library expansion exceeds the encoded module limit.', 'توسعه کتابخانه از حد ماژول ثبت‌شده بیشتر است.'],
  tape_expansion: ['Expansion eligibility depends on base-module revision, license and power supplies.', 'امکان توسعه به نسخه ماژول پایه، مجوز و منابع تغذیه وابسته است.'],
  tape_media: ['At least one selected tape drive cannot read/write this media generation.', 'حداقل یک درایو انتخاب‌شده نمی‌تواند این نسل نوار را بخواند یا بنویسد.'],
  tape_media_unknown: ['Drive/media generation compatibility is not encoded for this combination.', 'سازگاری نسل درایو و نوار برای این ترکیب ثبت نشده است.'],
  tape_capacity: ['Native tape capacity is used; compressed marketing capacity is not guaranteed.', 'ظرفیت بومی نوار استفاده می‌شود؛ ظرفیت تبلیغاتی فشرده‌شده تضمین‌شده نیست.'],
  host_protocol: ['Host protocol differs from the selected base system or tape drive.', 'پروتکل میزبان با سیستم پایه یا درایو نواری انتخاب‌شده متفاوت است.'],
  population: ['Drive population does not meet the documented per-node-pair requirement.', 'چیدمان درایوها حد مستند هر جفت نود را رعایت نمی‌کند.'],
  primera_media: ['Primera A controllers cannot use HDDs; C controllers cannot use NVMe in the encoded rule.', 'کنترلر Primera A با HDD و کنترلر C با NVMe طبق قاعده ثبت‌شده سازگار نیست.'],
  primera_base: ['Controller nodes exceed the selected storage base node capacity.', 'تعداد نودهای کنترلر از ظرفیت پایه ذخیره‌سازی بیشتر است.'],
  power_cords: ['Documented minimum power-cord count is not satisfied.', 'حداقل تعداد کابل برق مستند رعایت نشده است.'],
  qualification: ['Host/OS/HBA, firmware, cabling, licenses and supported topology require technical review.', 'میزبان، سیستم‌عامل، HBA، میان‌افزار، کابل‌کشی، مجوز و توپولوژی پشتیبانی‌شده نیازمند بررسی فنی است.'],
  performance_unknown: ['Measured IOPS, latency, throughput and recovery targets require workload validation.', 'IOPS، تأخیر، توان عملیاتی و اهداف بازیابی به اعتبارسنجی بار کاری نیاز دارند.'],
  file_gap: ['Validate the model-specific file protocol, software release and NAS/file topology.', 'پروتکل فایل، نسخه نرم‌افزار و توپولوژی NAS یا فایل مختص مدل بررسی شود.'],
  offline_gap: ['Plan an offline/offsite copy in addition to local disk backup.', 'علاوه بر پشتیبان دیسکی محلی، نسخه آفلاین یا خارج از سایت طراحی شود.'],
  immutable_gap: ['Verify retention locks, WORM media, software integration and key management.', 'قفل نگهداری، نوار WORM، یکپارچگی نرم‌افزار و مدیریت کلید بررسی شود.'],
  rpo_gap: ['Scheduled backup alone does not prove a sub-hour recovery point objective.', 'پشتیبان‌گیری زمان‌بندی‌شده به‌تنهایی هدف نقطه بازیابی زیر یک ساعت را ثابت نمی‌کند.'],
  base_unknown: ['No orderable base system was extracted for this model; advisory coverage only.', 'سیستم پایه قابل سفارش برای این مدل استخراج نشده؛ پوشش فقط مشاوره‌ای است.'],
  incomplete_answers: ['Complete the remaining questions to narrow the shortlist.', 'برای دقیق‌تر شدن پیشنهادها به پرسش‌های باقی‌مانده پاسخ دهید.'],
};

export function message(key, lang='fa', params={}) {
  if (!['fa','en'].includes(lang) || !Object.hasOwn(strings,key)) throw new Error('Unknown language or message');
  return strings[key][lang==='fa'?1:0].replace(/\{(\w+)\}/g,(_,name)=>String(params[name]??`{${name}}`));
}
export const messageKeys = Object.freeze(Object.keys(strings));
