import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as E from '../storage/engine.mjs';
import {message,messageKeys} from '../storage/copy.mjs';
const data=JSON.parse(readFileSync(new URL('../storage/catalog.json',import.meta.url),'utf8'));
let tests=0;
function test(name,fn){fn();tests++;console.log('PASS '+name);}
function opt(qs,sku){const o=data.options.find(o=>o.qs_id===qs&&o.sku===sku);assert(o,`Missing ${qs}:${sku}`);return o;}
function item(qs,sku,quantity=1){return {option_id:opt(qs,sku).id,quantity};}
function msa(){const s=E.initialConfiguration('msa-2060');s.host_protocol='fc';s.items=[item('16615','R0Q74B'),item('16615','R0Q47A',8)];s.diskGroups=[{option_id:opt('16615','R0Q47A').id,disks:8,spares:0,raid:'6',location:'base'}];return s;}
function tape(){const s=E.initialConfiguration('msl-msl2024');s.host_protocol='fc';s.items=[item('17271','AK379B'),item('17271','R6Q74A'),item('17271','Q2079A',24)];return s;}
const primary={purposes:['primary'],access:'block',workload:'virtualization',usableTB:10,annualGrowthPct:20,years:3,headroomPct:20,lifecycle:'active',budgetTier:'value'};
const backup={purposes:['backup'],backupTB:10,changePct:5,retentionDays:30,fullEveryDays:7,headroomPct:20,backupWindowHours:8,rtoHours:4};

test('Six storage families and source identity',()=>{
  assert.deepEqual(data.coverage.families,['alletra','msa','msl','nimble','primera','storeonce']);
  assert.equal(data.coverage.full_qualification,false);
  assert.equal(new Set(data.options.map(o=>o.id)).size,data.options.length);
  for(const x of [...data.models,...data.options,...data.rules]){
    assert(x.evidence.length);
    for(const e of x.evidence){assert.equal(e.end-e.start,e.quote.length);assert.equal(e.sha256.length,64);assert(data.documents.some(d=>d.id===e.qs_id&&d.sha256===e.sha256));}
  }
});
test('Every ordering row contains its exact SKU',()=>{for(const o of data.options){assert(o.evidence.some(e=>e.quote.includes(o.sku)));assert(o.model_ids.every(id=>data.models.some(m=>m.id===id&&m.qs_id===o.qs_id)));}});
test('Bilingual copy parity',()=>{for(const key of messageKeys)for(const lang of ['fa','en'])assert(message(key,lang));assert.match(E.nextQuestions({},'fa')[0].text,/[\u0600-\u06ff]/);assert.equal(E.nextQuestions({},'en')[0].key,'purposes');});
test('Conditional primary and backup discovery',()=>{const qs=E.nextQuestions({purposes:['primary','backup']},'en',50);assert(qs.some(q=>q.key==='access'));assert(qs.some(q=>q.key==='backupSoftware'));assert(qs.some(q=>q.key==='headroomPct'));assert(!qs.some(q=>q.key==='existingLTO'));});
test('Workload-specific performance questions',()=>{for(const workload of ['database','virtualization']){const q=E.nextQuestions({purposes:['primary'],workload},'en',50);assert(q.some(x=>x.key==='iops'));assert(q.some(x=>x.key==='latencyMs'));}assert(E.nextQuestions({purposes:['primary'],workload:'analytics'},'fa',50).some(x=>x.key==='sequentialMBps'));});
test('Unset values remain unknown',()=>{assert.equal(E.capacityPlan({usableTB:10}).status,'unknown');assert.equal(E.backupPlan({backupTB:10}).requiredTB,null);assert.equal(E.review(data,E.initialConfiguration('msa-2060')).status,'incomplete');});
test('Compound growth and TB/TiB reserve math',()=>{const p=E.capacityPlan(primary);assert(Math.abs(p.requiredTB-21.6)<1e-10);assert(Math.abs(p.requiredTiB-21.6/1.099511627776)<1e-10);});
test('Backup retention does not assume deduplication',()=>{const b=E.backupPlan(backup);assert.equal(b.fullCopies,5);assert.equal(b.incrementalCopies,25);assert.equal(b.retainedTB,62.5);assert.equal(b.requiredTB,78.125);assert.equal(b.assumptions.dataReductionRatio,1);assert(Math.abs(b.fullBackupMBps-347.2222222222)<1e-8);});
test('Falsy valid answers are retained',()=>{const r=E.validateRequirements({purposes:['archive'],offlineCopy:false,immutable:false,annualGrowthPct:0,years:0,existingLTO:0});assert.equal(r.offlineCopy,false);assert(!E.nextQuestions(r,'en',50).some(q=>q.key==='offlineCopy'));});
test('Invalid numbers, unknown fields and invalid choices rejected',()=>{for(const v of [NaN,Infinity,-1,'10'])assert.throws(()=>E.validateRequirements({usableTB:v}));assert.throws(()=>E.validateRequirements({headroomPct:100}));assert.throws(()=>E.validateRequirements({purposes:['bogus']}));assert.throws(()=>E.validateRequirements({retentionDays:1.5}));assert.throws(()=>E.validateRequirements({constructor:1}));assert.throws(()=>E.validateRequirements({purposes:null}));});
test('Purpose prevents primary storage from becoming backup or tape',()=>{const r=E.recommend(data,{...primary,purposes:['primary','backup','archive']},'en');assert(r.roles.primary.every(x=>['block','object'].includes(x.model.access)));assert(r.roles.backup.every(x=>['backup','secondary'].includes(x.model.access)));assert(r.roles.archive.every(x=>x.model.access==='tape'));assert(r.roles.primary[0].model.family==='msa');});
test('Retired models are explicitly opt-in with active lifecycle filter',()=>{const active=E.recommend(data,primary);assert(active.roles.primary.every(x=>x.model.lifecycle==='active_in_snapshot'));const both=E.recommend(data,{...primary,lifecycle:'allow_retired'});assert(both.roles.primary.some(x=>x.model.lifecycle==='retired_in_snapshot'));});
test('File, immutability, offline copy and short RPO gaps are visible',()=>{const r=E.recommend(data,{purposes:['primary','backup'],access:'file',immutable:true,offlineCopy:true,rpoMinutes:5},'en');assert(r.roles.primary.every(x=>x.model.access_modes.includes('file')));assert(r.roles.primary.some(x=>x.model.id==='alletra-x10000'));for(const k of ['file_gap','immutable_gap','offline_gap','rpo_gap'])assert(r.findings.some(f=>f.key===k));});
test('Cross-model and cross-generation options conflict',()=>{const o=opt('17254','S1H42A');assert.equal(E.optionCheck(data,'msa-2060',o.id).status,'conflict');assert.equal(E.optionCheck(data,'msa-2070',o.id).status,'listed');assert.equal(E.optionCheck(data,'msa-2072',o.id).status,'conflict');});
test('Unknown model scope remains unknown',()=>{const o=data.options.find(o=>o.scope==='unknown'&&o.model_ids.length);assert(o);assert.equal(E.optionCheck(data,o.model_ids[0],o.id).status,'unknown');});
test('Footnoted support matrices cannot become unconditional compatibility',()=>{const entries=data.options.filter(o=>o.conditional_matrix);assert(entries.length);for(const o of entries)assert.equal(o.scope,'unknown');});
test('A missing variant in a family matrix remains unknown',()=>{const o=data.options.find(o=>o.qs_id==='15933'&&o.category==='drive'&&!o.model_ids.includes('nimble-hf40c')&&!o.excluded_models.includes('nimble-hf40c'));assert(o);assert.equal(E.optionCheck(data,'nimble-hf40c',o.id).status,'unknown');assert(E.optionsFor(data,'nimble-hf40c','drive').some(x=>x.id===o.id));});
test('MSA homogeneous RAID6 is advisory, not qualified',()=>{const report=E.review(data,msa(),{},'en');assert(Math.abs(report.capacity.usableTB-11.52)<1e-10);assert.equal(report.capacity.basis,'raid_estimate');assert.equal(report.status,'needs_review');assert.equal(report.full_qualification,false);assert(report.findings.some(f=>f.key==='qualification'));});
test('RAID0 read-cache restriction and invalid RAID count',()=>{const s=msa();s.diskGroups[0].raid='0';assert(E.review(data,s).findings.some(f=>f.key==='raid'&&f.status==='conflict'));s.diskGroups[0].raid='6';s.diskGroups[0].disks=3;assert(E.review(data,s).findings.some(f=>f.key==='raid_count'));});
test('Drive allocation cannot exceed supplied quantity',()=>{const s=msa();s.diskGroups[0].disks=9;assert.equal(E.review(data,s).status,'blocked');assert(E.review(data,s).findings.some(f=>f.key==='allocation'));});
test('SFF drive in LFF base conflicts',()=>{const s=msa();s.items[0]=item('16615','R0Q73B');const r=E.review(data,s);assert(r.findings.some(f=>f.key==='form'));assert.equal(r.capacity.usableTB,null);});
test('MSA enclosure maximum is enforced',()=>{const s=msa();s.items.push(item('16615','R0Q40B',10));assert(E.review(data,s).findings.some(f=>f.key==='enclosure_count'));});
test('Host protocol mismatch is a known conflict',()=>{const s=msa();s.host_protocol='iscsi';assert(E.review(data,s).findings.some(f=>f.key==='host_protocol'));});
test('LTO9 media uses 18 TB native, not advertised 45 TB',()=>{const r=E.review(data,tape());assert.equal(r.capacity.tape.nativeTB,432);assert.equal(r.capacity.tape.slots,24);assert.equal(r.status,'needs_review');});
test('LTO8 drive rejects LTO9 media',()=>{const s=tape();s.items[1]=item('17271','Q6Q67A');assert(E.review(data,s).findings.some(f=>f.key==='tape_media'&&f.status==='conflict'));});
test('Existing LTO7 tapes cannot be read by LTO9 drives',()=>{assert(E.review(data,tape(),{existingLTO:7}).findings.some(f=>f.key==='tape_media'&&f.status==='conflict'));});
test('Tape drives cannot exceed library drive bays',()=>{const s=tape();s.items[1].quantity=3;assert(E.review(data,s).findings.some(f=>f.key==='tape_drives'));});
test('StoreOnce local capacity excludes effective data reduction',()=>{const s=E.initialConfiguration('storeonce-3760');s.items=[item('14996','S4P73A')];assert.equal(E.review(data,s).capacity.usableTB,108);s.items.push(item('14996','S4P75A'));assert.equal(E.review(data,s).capacity.usableTB,216);s.items[1].quantity=2;assert.equal(E.review(data,s).status,'blocked');});
test('StoreOnce 3720 complicated enablement stays unresolved',()=>{const s=E.initialConfiguration('storeonce-3720');s.items=[item('14996','S4P72A')];assert.equal(E.review(data,s).capacity.usableTB,18);s.items.push(item('14996','S4P74A'));assert.equal(E.review(data,s).capacity.usableTB,null);});
test('Vendor flash capacity is not inferred from generic RAID math',()=>{const m=data.models.find(m=>m.id==='nimble-af20');const drive=data.options.find(o=>o.model_ids.includes(m.id)&&o.category==='drive'&&o.attributes.capacity_tb&&o.attributes.pack_qty>=4);assert(drive);const base=data.options.find(o=>o.model_ids.includes(m.id)&&o.category==='base');const s=E.initialConfiguration(m.id);s.items=[{option_id:base.id,quantity:1},{option_id:drive.id,quantity:1}];s.diskGroups=[{option_id:drive.id,disks:drive.attributes.pack_qty,spares:0,raid:'6',location:'base'}];assert.equal(E.review(data,s).capacity.usableTB,null);});
test('Malicious or malformed configuration imports rejected',()=>{for(const value of [null,{},[],{schema_version:2}])assert.throws(()=>E.validateConfiguration(value,data));const s=msa();s.items[1].quantity=Infinity;assert.throws(()=>E.validateConfiguration(s,data));s.items[1].quantity=8;s.items.push({...s.items[0]});assert.throws(()=>E.validateConfiguration(s,data));});
test('Reports include unresolved findings and formula-safe exports',()=>{const report=E.review(data,msa(),{},'en');assert(E.exportJSON(report).includes('qualification'));const mutated={...report,bom:[{...report.bom[0],description:'  =HYPERLINK("bad")'}]};const csv=E.exportCSV(mutated);assert(csv.startsWith('\uFEFF'));assert(csv.includes("'  =HYPERLINK"));assert(csv.includes('TECHNICAL REVIEW'));assert(csv.includes('qualification'));});
test('Engine calls do not mutate input data',()=>{const s=msa(),before=JSON.stringify({data,s,primary});E.review(data,s,primary);E.recommend(data,primary);E.nextQuestions(primary);assert.equal(JSON.stringify({data,s,primary}),before);});
console.log(`${tests} storage checks passed.`);
